/* Puts a brand in place (electron/brands/<id>/):

     node tools/brand.ts [generic]     default: $STUDIO_BRAND, else generic

   - src/brand.ts re-exports brands/<id>/brand.ts (the only import of a brand,
     so a bundle carries that one only);
   - brands/<id>/assets/ is copied to src/renderer/assets/brand/ (emptied
     first: nothing of an earlier brand is left).
   Both are generated (.gitignore).  tools/build-ui.ts and tools/package.ts
   call this first. */

import { cpSync, existsSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.join(import.meta.dirname, '..');
export const BRANDS = ['generic'] as const;
export type BrandId = typeof BRANDS[number];

export function brandId(arg?: string): BrandId {
  const id = arg ?? process.env.STUDIO_BRAND ?? 'generic';
  if (!(BRANDS as readonly string[]).includes(id)) throw new Error(`unknown brand "${id}" (${BRANDS.join(', ')})`);
  return id as BrandId;
}

export function useBrand(id: BrandId): void {
  writeFileSync(path.join(root, 'src/brand.ts'),
    `// Generated by tools/brand.ts: the brand in use.\nexport { brand } from '../brands/${id}/brand.ts';\n`);
  const to = path.join(root, 'src/renderer/assets/brand');
  rmSync(to, { recursive: true, force: true });
  const from = path.join(root, 'brands', id, 'assets');
  if (existsSync(from)) cpSync(from, to, { recursive: true });
}

if (import.meta.main) {
  const id = brandId(process.argv[2]);
  useBrand(id);
  console.log(`brand: ${id}`);
}
